### ISSUE TITLE
【功能请求】将来考虑做批量下载功能吗？

### ISSUE THREAD

**Issue by PumpkinSin** [Howardzhangdqs/zhihu-copy-as-markdown#1]

**Comment by Howardzhangdqs** [comment]
是一个问题下的所有回答一起下吗

我现在就开整

**Comment by Howardzhangdqs** [comment]
不用将来，现在就写

**Comment by Howardzhangdqs** [comment]
@PumpkinSin 做好了

**Comment by PumpkinSin** [comment]
> @PumpkinSin 做好了

谢谢……其实我想要类似[这个项目](https://github.com/YaoZeyuan/zhihuhelp)自动爬取单个账号（其实只想备份自己的），但这个只能导出单页html或者epub，，，

**Comment by Howardzhangdqs** [comment]
> > @PumpkinSin 做好了
> 
> 谢谢……其实我想要类似[这个项目](https://github.com/YaoZeyuan/zhihuhelp)自动爬取单个账号（其实只想备份自己的），但这个只能导出单页html或者epub，，，

Emm sry 要实现这个功能Tampermonkey就有点不够用了，得要浏览器插件了。之前有人提过这个功能：<https://greasyfork.org/zh-CN/scripts/478608/discussions/213359>，但是最后我发现实现不了。

主要是向知乎发送的请求都要加签，新的加签算法网上我还没找到有人破解成功的

**Comment by PumpkinSin** [comment]
> > > @PumpkinSin 做好了
> > 
> > 
> > 谢谢……其实我想要类似[这个项目](https://github.com/YaoZeyuan/zhihuhelp)自动爬取单个账号（其实只想备份自己的），但这个只能导出单页html或者epub，，，
> 
> Emm sry 要实现这个功能Tampermonkey就有点不够用了，得要浏览器插件了。之前有人提过这个功能：https://greasyfork.org/zh-CN/scripts/478608/discussions/213359，但是最后我发现实现不了。
> 
> 主要是向知乎发送的请求都要加签，新的加签算法网上我还没找到有人破解成功的

让每个page的“阅读全文”自动展开然后下载呢？这样至少可以一页一页下载。
