### ISSUE TITLE
批量下载功能在个别知乎问题无法下载

### ISSUE THREAD

**Issue by gikillu** [Howardzhangdqs/zhihu-copy-as-markdown#2]
您好，这个批量下载功能非常实用，只是批量下载功能在个别知乎问题显示下载成功，但实际没有下载成功，您可以看下是哪里出了问题吗

比如这个https://www.zhihu.com/question/646080781

**Comment by Howardzhangdqs** [comment]
感谢提醒，我周末抽空修修看

**Comment by Howardzhangdqs** [comment]
今天发烧没去上学，刚修了一下，您试试看？ @gikillu

**Comment by gikillu** [comment]
可以下载了，非常感谢，批量下载的功能确实是好用
最后有几个小的问题，想请问一下
批量下载功能中，
问题描述文件夹的命名，和回答的文件夹命名区分不大（问题+一串数字或一串字母），以后会考虑将问题描述的文件夹修改地更明显吗？
问题描述需要展开后才能和回答一起打包下载，以后会考虑添加，问题描述自动展开的功能吗？
会考虑添加，知乎回答自动向下加载然后再批量下载的功能吗？

**Comment by Howardzhangdqs** [comment]
我刚刚理解错您意思了，打了一大段话，懒得删了，简单来说就是我改好了，更新插件一下就行

文件名（问题+一串数字或一串字母）里的 一串数字  在一般的回答下是 这个回答的知乎里的编号

比如您给的链接 https://www.zhihu.com/question/646080781

question/后面的646080781就是这个回答的编号，因为我找了半天感觉只有这个不会重复，所以就用作文件名了。

您提的这个issue的原因是我的插件没能读出部分问题下回答的编号，导致插件卡bug了，修复方法是用八位数字+字母代替原本的编号。

---

自动展开功能我推荐 @XIU2 大佬做的知乎增强插件：https://greasyfork.org/zh-CN/scripts/419081

我特意为这个插件做了兼容，我的和他的插件正常情况下不会冲突。

**Comment by gikillu** [comment]
感谢解答，按照您的方法试过了，效果很好

**Comment by gikillu** [comment]
> 希望以后可以考虑添加

回答时间、编辑时间、赞数、赞数这些内容

我找到一个根据您这个项目开发的仓库，具有部分上述功能，但没有批量下载的功能。
_[https://github.com/qtqz/zhihu-backup-collect?tab=readme-ov-file]_

![屏幕截图 2024-03-26 161802](https://github.com/Howardzhangdqs/zhihu-copy-as-markdown/assets/106650106/8a7874f0-d8f7-40e1-90f5-4624611cb198)


>另外，问题的时间进展脉络，这个可以一起下载吗


![屏幕截图 2024-03-26 163721](https://github.com/Howardzhangdqs/zhihu-copy-as-markdown/assets/106650106/11db164d-bc82-4125-a3a2-c39de5db1f42)

**Comment by Howardzhangdqs** [comment]
可以考虑，但先请等我毕业

我现在高三马上要高考了，学业比较繁忙🙏😇

**Comment by gikillu** [comment]
加油，祝你取得理想的成绩
如果到时有学校和专业选择的疑问，欢迎来找我
